### ISSUE TITLE
use with zend-diactoros psr7 request object

### ISSUE THREAD

**Issue by newbie78** [ventoviro/windwalker-http#1]
In the method `\Zend\Diactoros\Request::withHeader` header value is checked for strict compliance of the type. available only either string or array.
But for example in `\Windwalker\Http\Transport\CurlTransport::doRequest` when calling withHeader value is passed integer `strlen($options[CURLOPT_POSTFIELDS])`

We should add a cast to string for example `$request = $request->withHeader('Content-Length', (string)strlen($options[CURLOPT_POSTFIELDS]));`

**Comment by asika32764** [comment]
Thank you for reporting this issue, I moved issue to primary repo, see https://github.com/ventoviro/windwalker/issues/428
