### ISSUE TITLE
CurlTransport: curl_error not being checked every time

### ISSUE THREAD

**Issue by jmshelby** [ventoviro/windwalker-http#2]
I noticed here below, that `curl_error` is only checked if content was returned, and only if configured as well.

https://github.com/ventoviro/windwalker-http/blob/07eeaebcec7acbb58f6ccc0d1ec51e869a232de2/Transport/CurlTransport.php#L39-L42

However, there are many errors that can occur, even though content *has* been returned. One example is: `18 - transfer closed with outstanding read data remaining`.

As far as I can tell, there is no way to configure your lib, such that it can catch errors like this "curl 18", and throw them as runtime exceptions?

**Comment by asika32764** [comment]
Yes, it seems should check error after every request, please wait for next release.

**Comment by asika32764** [comment]
Move to main repository
